### ISSUE TITLE
Feature Request: Cross-Realm Price.

### ISSUE THREAD

**Issue by Battler624** [kalilistic/PriceCheck#10]
Show cross realm price on hover or while holding a button

**Comment by kalilistic** [comment]
I didn't put this in originally since the goal of pricecheck was to keep things pretty simple. There's already the market board plugin that I think might be better suited for this. I'll think about it though and leave this open to see if there is interest.

**Comment by Battler624** [comment]
If its not too much work, and whenever you are free, please add it.

**Comment by kalilistic** [comment]
Closing for now for the reasons mentioned above. Thanks.
