### ISSUE TITLE
PriceCheck window opens automatically upon login

### ISSUE THREAD

**Issue by RhapsodySL** [kalilistic/PriceCheck#11]
PriceCheck's window currently opens automatically upon logging in which isn't particularly useful; this doesn't reflect the behavior of most other Dalamud addons and is more of a nuisance since you're unlikely to need to use PriceCheck every time you log in. This should either be disabled or an option should be added to do so.

**Comment by kalilistic** [comment]
That's fair, I'll add this in next release.

**Comment by kalilistic** [comment]
This is now available in testing as a toggle in settings.
