### ISSUE TITLE
Improvements to the UI

### ISSUE THREAD

**Issue by RhapsodySL** [kalilistic/PriceCheck#12]
At the moment if you pricecheck an item, you'll get a decently large number of items that are either under the pricing threshold or don't have any available pricing info. It would be ideal if these could be filtered out of the data similar to how unmarketable items are.

Another improvement would be to introduce a button to the UI that allows you to clear your pricechecking history; this is most notably useful if you're pricechecking another batch of items and don't want to get anything mixed up, among other reasons.

A final improvement would be to perhaps have the addon window automatically open if you're holding down the hotkey when hovering over an item (as at the moment the window already needs to be open). It would additionally be useful to show the hotkey on the pricechecking window (probably in the titlebar) to reference for people that don't use the addon that much.

**Comment by kalilistic** [comment]
These are good ideas, will add them next release.

**Comment by kalilistic** [comment]
These are now available in settings as new options. Thanks for the ideas - let me know how it goes.
For clearing history - I added this but as a menu. Just right click on any items in the list.
