### ISSUE TITLE
PriceCheck error on startup and hover delay not working

### ISSUE THREAD

**Issue by trowieuk** [kalilistic/PriceCheck#14]
I get a pop up saying PriceCheck ran into an error, it continues to work but the hover delay has stopped working.
I've got it set to 2 and when I hover over an item it does wait 2 seconds, but then it instantly starts processing any other items I hover over. Was fine until last update to PriceCheck.

**Comment by kalilistic** [comment]
What is the error? Do you keep getting it or just once after installing the update?

**Comment by trowieuk** [comment]
I don't see an error code just a pop up saying an error has happened and to report it. 
https://i.imgur.com/LQC6jht.png
I get that every time I start FF, the plugin continues to work but the hover delay only works for one item then it just processes other items with no delay, also can't open config with button or command.

**Comment by trowieuk** [comment]
https://www.youtube.com/watch?v=YnKqdoHWa1Q

Other than the mouse not showing properly hopefully the video shows a bit more of what I mean by hover delay not working, it's set as 2 seconds hover delay. You can see the hover effect anyway so should be able to see I am quickly hovering and it's still processing.

**Comment by jasinkare** [comment]
Having similar issues (on testing, unsure if there is a difference right now), without any visible errors. Config checkboxes also seem to be getting reset without changing the actual settings, specifically on the chat tab. Had turned off chat stuff to cope, probably why I'm not getting an error. Issue has persisted through client and PC restarts. Behavior is similar to the video posted above. My hover delay is 8 seconds.

**Comment by kalilistic** [comment]
hey, this is fixed but just waiting on merge. this is specific to test. I'll reply here once live.

**Comment by trowieuk** [comment]
Just tried 2.0.56, working as intended now, thank you very much! 👍 😄

**Comment by kalilistic** [comment]
This has been merged to testing too.

**Comment by kalilistic** [comment]
Closing since think this all sorted. Let me know if still any issues.
