### ISSUE TITLE
This might be dumb

### ISSUE THREAD

**Issue by Relazed** [kalilistic/PriceCheck#15]
Sooo, I'm trying to get this to work, but there's no read me where it says where you put the files after download and unzip. Should I put the master map in the ffxiv directory or do I copy the first page in the master map and paste those files in the directory? or is it another place I need to put it?

**Comment by kalilistic** [comment]
Hey, the releases are there only for experimental releases (they get unzipped into dev plugins). But for most cases, you'll want to install plugins through the launcher.  https://goatcorp.github.io/faq/dalamud_troubleshooting#q-how-do-i-installenable-plugins
