### ISSUE TITLE
Unable to price check items in inventory

### ISSUE THREAD

**Issue by colbycheeze** [kalilistic/PriceCheck#17]
Price check works when items are equipped, but not for anything that is moused over from the inventory.

**Comment by colbycheeze** [comment]
To clarify, when not using keybind it works but with keybind it does not.

**Comment by kalilistic** [comment]
Are you holding the keybind before mousing over the item?

**Comment by abb0r** [comment]
I have the same problem. Maybe it has something to do with that I have bound Shift and Tab to something other  in game?

**Comment by kalilistic** [comment]
Ah, could be conflicting. I also have overhauled this on the API4/Testing version too - so you can press keybind before or after. It'll be on main in a few weeks once API4 is live.

**Comment by kalilistic** [comment]
Closing for now, let me know if have issues on API4.
