### ISSUE TITLE
Price Check hotkey doesn't seem to work

### ISSUE THREAD

**Issue by SkyAphid** [kalilistic/PriceCheck#19]
Hello, this plugin seems extremely useful, so I installed it.

However, I don't know if the instructions are just unclear and I'm not using it right, but it doesn't appear to work. When I hover over an item in my inventory and press shift, or z, or both at the same time, the item doesn't appear in the PriceCheck Overlay. Is this bug, or am I just using it wrong?

Thank you for your time!

**Comment by kalilistic** [comment]
Are you on API3 or API4? If you're on API3, you need to hold the keybind BEFORE hovering over the item.
If you are on API4, either works. API4 will be going live on 10/10 or there are instructions in discord on how to switch early.

**Comment by SkyAphid** [comment]
I'm simply using the version available in the ingame menu of XIVLauncher. Is that an old version?

**Comment by kalilistic** [comment]
It's technically still the main version but there's been a big overhaul (api4) that'll get released on 10/10.

**Comment by kalilistic** [comment]
API4 has been released and this should be fixed.

**Comment by SkyAphid** [comment]
Thank you for your time!! I'll check it out later!
