### ISSUE TITLE
Chat notifications not following Dalamud chat channel setting

### ISSUE THREAD

**Issue by Farsinian** [kalilistic/PriceCheck#2]
Would it be possible for PriceCheck's results in chat to follow Dalamud's setting? Right now it is printing to all channels at once, and there is no way I can see to restrict it from certain chat logs and have it visible in others.

**Comment by kalilistic** [comment]
Hey, sure. I'll look at adding this for an upcoming release.

**Comment by Farsinian** [comment]
Thanks for taking a look at it!
