### ISSUE TITLE
Support for new Dalamud version

### ISSUE THREAD

**Issue by brandonam** [kalilistic/PriceCheck#20]
Is there any work planned to support the new dalamud version on .NET 5.0.6?

**Comment by kalilistic** [comment]
Hey, PriceCheck should be working on the new version. Might try deleting the old copy and reinstalling fresh.

**Comment by brandonam** [comment]
I needed to add your neat plugins repo to the custom plugins section in order for it to show :) but its there now. Unfortunately seems it no longer part of the default list of plugins and even with using this method it doesn't seem to be logging anything to the chat window or the pricecheck dialog. 

Please let me know if there is any log I can help provide. I found this in dalamud.log, but unfortunately I'm not sure how helpful it is.

https://pastebin.com/YrSbGMnj

**Comment by kalilistic** [comment]
The "neat plugins" is a site only - not a custom repo. So I think it's probably ignored in the list. This sounds like a more general launcher problem as I can see PriceCheck in the official repos. I think best bet would be to join the discord for this issue. https://discord.gg/3NMcUV5
