### ISSUE TITLE
Suggestion: Can we have an option to just check the current minimum price of an item?

### ISSUE THREAD

**Issue by kzcheng** [kalilistic/PriceCheck#5]
Hey there, can we have an option to just check the current minimum price of an item?

As in, just check on Universalis, and grab the cheapest price of an item on sale on my world?

For example, if Universalis says the cheapest "Weathered Earrings" on my world is 2940, just grab that number and show it to the user?

This feels like what me, as a seller, needs to know the most. Since for most of my random items, I just want to sell them at the lowest price possible.

Thanks!

**Comment by kalilistic** [comment]
I did consider this originally...but I didn't add it yet as universalis data is not usually reliable enough for this given it's crowd-sourced. Hopefully this will change as more people contribute.

**Comment by kalilistic** [comment]
This is now available on testing.
