### ISSUE TITLE
Feature Request: Overlay fadeout when pricecheck isn't being used

### ISSUE THREAD

**Issue by rushtothesun** [kalilistic/PriceCheck#6]
Hi, could you consider adding an option that turns off the PriceCheck Overlay after X amount of seconds of not price checking an item. Mainly I want to be able to hold my keybind to price check an item, the overlay popups and tells me the price, and then after 3 seconds the overlay disappears so it's not cluttering my screen.

**Comment by kalilistic** [comment]
I can look at adding this for the next release.

**Comment by rushtothesun** [comment]
> 
> 
> I can look at adding this for the next release.

Thanks, appreciate it!

**Comment by kalilistic** [comment]
This is now available on testing.

**Comment by rushtothesun** [comment]
> 
> 
> This is now available on testing.

Works perfectly, thanks!
